# Generated by Django 4.2.3 on 2023-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srviciosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_externa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
